### ISSUE TITLE
Make the extension accessible

### ISSUE THREAD

**Issue by julien-deramond** [julien-deramond/bootstrap-deprecated-classes-extension#11]
### Description

Right now, the extension will detect the deprecated classes, and inject some CSS to highlight these classes; something like:

```css
.bootstrap-browser-extension-bs-4 {
  & .ml-md-auto {
    &::before {
      color: #000;
      background-color: rgb(189, 127, 127);
      padding: 2px;
      border: 2px solid black;
      z-index: 10000;
      content: '.ml-md-auto';
}
```

However, it doesn't allow screen readers to use the extension.

Maybe we could also inject a screen-reader-only span (or something like this) in the DOM to detect the deprecated classes. Let's study if there's a way to do it.
